DEFAULT_MODEL_NAME = ""
DEFAULT_MAX_TOKENS = 8000
DEFAULT_TEMPERATURE = 0.3

MAX_TOOL_ITERATIONS = 100
MAX_CALL_TIMES = 30

AUTO_COMPACT_THRESHOLD = 0.85
COMPACT_KEEP_RECENT = 10

STREAM_INTERVAL = 0.3

MEMORY_FILE_NAME = "CLAUDE.md"
MAX_MEMORY_LENGTH = 2000
